**Step-1: Import required packages**

In [4]:
import pandas as pd                      # Dataframe operations
import numpy as np                       # Math operations
import matplotlib.pyplot as plt          # Plotting
import seaborn as sns                    # Plotting

**Step-2: Create a Dataframe using A list**

In [8]:
names = ['Ramesh','Suresh','Mahesh']
age = [20,22,24]
pd.DataFrame(zip(names,age))

        0   1
0  Ramesh  20
1  Suresh  22
2  Mahesh  24

**pd.DataFrame**

- data = None
- index   : Index or array like  Eg: array([1,2,3])
- columns : Index or array-lime

In [13]:
names = ['Ramesh','Suresh','Mahesh']
age = [20,22,24]
pd.DataFrame(names,age)

         0
20  Ramesh
22  Suresh
24  Mahesh

**Step-3: Add the column names**

In [16]:
names = ['Ramesh','Suresh','Mahesh']
age = [20,22,24]
cols = ['Names','Age']
pd.DataFrame(zip(names,age),columns=cols)

    Names  Age
0  Ramesh   20
1  Suresh   22
2  Mahesh   24

**Step-4: Change the Index**

In [21]:
names = ['Ramesh','Suresh','Mahesh']
age = [20,22,24]
cols = ['Names','Age']
idx = ['A','B','C']
#pd.DataFrame(data,index,columns)
pd.DataFrame(zip(names,age),index=idx,columns=cols)

    Names  Age
A  Ramesh   20
B  Suresh   22
C  Mahesh   24

**Step-5 Create Empty DataFrame and update the Dataframe**

In [ ]:
# Above one we created dataframe with values directly
# Now first we will create empty dataframe
# then will add the values

In [24]:
df = pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [26]:
names = ['Ramesh','Suresh','Mahesh']
df['Names']= names
df['Age'] = [20,22,24]
df

    Names  Age
0  Ramesh   20
1  Suresh   22
2  Mahesh   24

In [28]:
df = pd.DataFrame()
df['Names']= ['Ramesh','Suresh','Mahesh']
df['Age'] = [20,22,24]
df

    Names  Age
0  Ramesh   20
1  Suresh   22
2  Mahesh   24

In [30]:
df['Age']=[30,32,34] #updating
df['age']=[100,200,300] # creating
df['City'] = ['Hyderabad','Bangalore','Chennai']# creating
df

    Names  Age  age       City
0  Ramesh   30  100  Hyderabad
1  Suresh   32  200  Bangalore
2  Mahesh   34  300    Chennai

**Notes**

- Python is case sensitive
- 'Age' and 'age' both are different
- updated column values always should be length of dataframe
- Dont expect null like sql if we miss any value

**Step-6: Drop the column**

- labels: 
- axis: 'Axis' = 0,
- index: 
- columns: 
- inplace: 'bool' = False,

In [37]:
df.drop(2)

    Names  Age  age       City
0  Ramesh   30  100  Hyderabad
1  Suresh   32  200  Bangalore

In [51]:
df.drop([1,2]) # Multiple= List

    Names  Age  age       City
0  Ramesh   30  100  Hyderabad

In [53]:
df.drop(2,axis=0)

    Names  Age  age       City
0  Ramesh   30  100  Hyderabad
1  Suresh   32  200  Bangalore

In [69]:
df.drop(2,axis=1)

KeyError: '[2] not found in axis'

In [55]:
df.drop(columns=['age'])

    Names  Age       City
0  Ramesh   30  Hyderabad
1  Suresh   32  Bangalore
2  Mahesh   34    Chennai

In [57]:
df.drop(index=[2])

    Names  Age  age       City
0  Ramesh   30  100  Hyderabad
1  Suresh   32  200  Bangalore

In [59]:
df.columns

Index(['Names', 'Age', 'age', 'City'], dtype='object')

In [61]:
df.columns[2]

'age'

In [63]:
df.drop('age',axis=1)

    Names  Age       City
0  Ramesh   30  Hyderabad
1  Suresh   32  Bangalore
2  Mahesh   34    Chennai

In [65]:
df.drop(columns=['age'], inplace=True)

In [67]:
df

    Names  Age       City
0  Ramesh   30  Hyderabad
1  Suresh   32  Bangalore
2  Mahesh   34    Chennai

In [ ]:
#Assignment-1
df.rename()

#Assignment-2
df.shape
df.size
df.columns
df.isnull()
len(df)
df.info
df.drop_duplicates
df.dtypes